spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://ddmscloud-db-mysql:3306/ddmscloud_admin?characterEncoding=utf8&useSSL=false

mybatis:
  type-aliases-package: com.mpisi.ddmscloud.provider.admin.model.domain
  mapper-locations: classpath:mapper/*.xml,classpath*:sdk/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers: com.mpisi.ddmscloud.common.core.mybatis.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

liquibase:
  change-log: classpath:liquibase/index.xml
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  url: ${spring.datasource.url}

security:
  oauth2:
    client:
      clientId: ddmscloud-client-admin
      clientSecret: ddmscloudClientSecret
      access-token-uri: http://ddmscloud-gateway:7979/admin/oauth/token
      user-authorization-uri: http://ddmscloud-gateway:7979/admin/oauth/authorize
    resource:
      id: ddmscloud-resource-admin
      filter-order: 3

ddmscloud:
  enableSqlLogInterceptor: false
  aliyun:
    rocketMq:
      enable: true
      reliableMessageConsumer: false
      reliableMessageProducer: true
      instanceName: ddmscloud-provider-admin
      consumerGroup: CID_ADMIN
      producerGroup: PID_ADMIN
  auth:
    rest-pwd-url: http://dev-login.ddmscloud.net/resetPwd?resetPwdKey=
    active-user-url: http://dev-api.ddmscloud.net:7979/admin/auth/activeUser/
    refresh-token-url: http://dev-api.ddmscloud.net:7979/admin/oauth/token
  token:
    interceptor:
      enable: true
  oauth2:
    jwtSigningKey: ddmscloud
    client:
      id: ${security.oauth2.resource.id}
      accessTokenUrl: ${security.oauth2.client.access-token-uri}
      clientId: ${security.oauth2.client.clientId}
      clientSecret: ${security.oauth2.client.clientSecret}
      clientAuthenticationScheme: header
  security:
    social:
      filterProcessesUrl: /auth/callback
      qq:
        app-id: 101431061
        app-secret: 0154c848f45fc705412462d4f99a592c
        providerId: qq
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
        providerId: weixin
    code:
      image:
        expireIn: 180
        url: /auth/register,/auth/submitResetPwdEmail,/auth/code/sms
      sms:
        expireIn: 600
        url: /admin/auth/submitResetPwdPhone
        mobileMaxSendCount: 1
        ipMaxSendCount: 2
        totalMaxSendCount: 3
    oauth2:
      tokenStore: jwt
      clients[0]:
        clientId: ddmscloud-client-admin
        clientSecret: ddmscloudClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"
      clients[1]:
        clientId: ddmscloud-browser
        clientSecret: ddmscloudClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"
      clients[2]:
        clientId: ddmscloud-client-gateway
        clientSecret: ddmscloudClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"
      clients[3]:
        clientId: ddmscloud-client-zipkin
        clientSecret: ddmscloudClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"
      clients[4]:
        clientId: ddmscloud-client-datacenter
        clientSecret: ddmscloudClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"
      clients[5]:
        clientId: ddmscloud-client-order
        clientSecret: ddmscloudClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"
      clients[6]:
        clientId: ddmscloud-client-openplatform
        clientSecret: ddmscloudClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"
      clients[7]:
        clientId: ddmscloud-client-job
        clientSecret: ddmscloudClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"