spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
  cache:
    cache-names: datacenter-cache
  datasource:
    url: jdbc:mysql://ddmscloud-db-mysql:3306/ddmscloud_datacenter?characterEncoding=utf8&useSSL=false

liquibase:
  change-log: classpath:liquibase/index.xml
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  url: ${spring.datasource.url}

mybatis:
  type-aliases-package: com.mpisi.ddmscloud.provider.datacenter.model.domain
  mapper-locations: classpath:mapper/*.xml,classpath*:sdk/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers: com.mpisi.ddmscloud.common.core.mybatis.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

security:
  oauth2:
    client:
      clientId: ddmscloud-client-datacenter
      clientSecret: ddmscloudClientSecret
      access-token-uri: http://ddmscloud-gateway:7979/admin/oauth/token
      user-authorization-uri: http://ddmscloud-gateway:7979/admin/oauth/authorize
    resource:
      user-info-uri: http://ddmscloud-gateway:7979/admin/user
      prefer-token-info: false
      jwt:
        key-uri: http://ddmscloud-provider-admin:8000/oauth/token_key

ddmscloud:
  enableSqlLogInterceptor: false
  dingTalk:
    webhookToken:
      sendException: 7b0fcc73f3d2be1415c5d31e5b34100c689961454af15a61635749ba0d8*****
      jobListener: 7b0fcc73f3d2be1415c5d31e5b34100c689961454af15a61635749ba0d8*****
  token:
    interceptor:
      enable: true
  zk:
    zkAddressList: ddmscloud-provider-zk:2181
  aliyun:
    rocketMq:
      enable: false
      reliableMessageConsumer: false
      reliableMessageProducer: true
      namesrvAddr: ddmscloud-mq-rocket:9876
      instanceName: ddmscloud-provider-datacenter
      consumerGroup: CID_DATACENTER
      producerGroup: PID_DATACENTER
  oauth2:
    jwtSigningKey: ddmscloud
    client:
      id: ${security.oauth2.resource.id}
      accessTokenUrl: ${security.oauth2.client.access-token-uri}
      clientId: ${security.oauth2.client.clientId}
      clientSecret: ${security.oauth2.client.clientSecret}
      clientAuthenticationScheme: header
      tokenStore: jwt