spring:
  cache:
    cache-names: job-cache
  datasource:
    url: jdbc:mysql://ddmscloud-db-mysql:3306/ddmscloud_job?characterEncoding=utf8&useSSL=false

liquibase:
  change-log: classpath:liquibase/index.xml
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  url: ${spring.datasource.url}

mybatis:
  type-aliases-package: com.mpisi.ddmscloud.provider.job.model.domain
  mapper-locations: classpath:mapper/*.xml,classpath*:sdk/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers: com.mpisi.ddmscloud.common.core.mybatis.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

security:
  oauth2:
    client:
      clientId: ddmscloud-client-job
      clientSecret: ddmscloudClientSecret
      access-token-uri: http://ddmscloud-gateway:7979/admin/oauth/token
      user-authorization-uri: http://ddmscloud-gateway:7979/admin/oauth/authorize
    resource:
      user-info-uri: http://ddmscloud-gateway:7979/admin/user
      prefer-token-info: false
      jwt:
        key-uri: http://ddmscloud-provider-admin:8000/oauth/token_key

ddmscloud:
  enableSqlLogInterceptor: false
  dingTalk:
    webhookToken:
      jobListener: 7b0fcc73f3d2be1415c5d31e5b34100c689961454af15a61635749ba0d8*****
  token:
    interceptor:
      enable: true
  message:
    maxSendTimes: 7
    handleTimeout: 5
    resendMultiplier: 2
  aliyun:
    rocketMq:
      enable: false
      reliableMessageConsumer: false
      reliableMessageProducer: true
      namesrvAddr: ddmscloud-mq-rocket:9876
      instanceName: ddmscloud-provider-job
      producerGroup: PID_JOB
  oauth2:
    jwtSigningKey: ddmscloud
    client:
      id: ${security.oauth2.resource.id}
      accessTokenUrl: ${security.oauth2.client.access-token-uri}
      clientId: ${security.oauth2.client.clientId}
      clientSecret: ${security.oauth2.client.clientSecret}
      clientAuthenticationScheme: header
      tokenStore: jwt
  zk:
    zkAddressList: ddmscloud-provider-zk:2181
    namespace: ddmscloud-elastic-job
  job:
    task:
      dingTalk:
        cron: 0 0/20 * * * ?
        shardingTotalCount: 1
        shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
      sendingMessage:
        cron: 0 0/20 * * * ?
        shardingTotalCount: 1
        jobParameter: fetchNum=200,taskType=SENDING_MESSAGE
      waitingMessage:
        cron: 0 0/20 * * * ?
        shardingTotalCount: 1
        jobParameter: fetchNum=200,taskType=WAITING_MESSAGE

dataflowJob:
  cron: 0 */20 * * * ?
  shardingTotalCount: 1
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou